#!/bin/bash

# 装饰等待效果函数
function waiting()
{
  i=0
  while [ $i -le 100 ]
  do
    for j in '\' '|' '/' '--'
    do
      printf "\t\t\t\t%c%c%c%c%c 启动中... %c%c%c%c%c\r" \
      "$j" "$j" "$j" "$j" "$j" "$j" "$j" "$j" "$j" "$j"
      sleep 0.1
    done
    let i+=10
  done
}

# 查找进程postgres进程是否存在
true_pid=`ps -ef | grep postgres | grep -v "su" | grep -v "grep" | awk '{print $2}'`

current_pwd=`pwd`
cd /opt/modules/other_command_home

if [[ $true_pid != "" ]]
then 
  #echo "pid = $true_pid"
  echo "postgresql已启动"
  echo "重启postgresql..."
  echo 'cytest' | su -c "/opt/modules/postgresql/bin/restart-pgsql" postgres
  echo "重启postgresql完毕"
else
  echo "postgresql未启动"
  sleep 1
  echo "启动postgresql..."
  sleep 1
  echo 'cytest' | su -c "/opt/modules/postgresql/bin/start-pgsql" postgres
  echo "启动postgresql完毕"
fi

sleep 1

echo "配置superset..."
cd /opt/modules/superset_v/
source /opt/modules/superset_v/bin/activate
sleep 1
echo "配置superset完毕"
echo "启动superset..."

cd $current_pwd
waiting
echo
sleep 1

superset run -h -p --with-threads --reload --debugger
